// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Get(ctx interface{}, key interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(s string, err error) *MockClient_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type MockClient
func (_mock *MockClient) Increment(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (int64, error)); ok {
		return returnFunc(ctx, key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) int64); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockClient_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockClient_Expecter) Increment(ctx interface{}, key interface{}, ttl interface{}) *MockClient_Increment_Call {
	return &MockClient_Increment_Call{Call: _e.mock.On("Increment", ctx, key, ttl)}
}

func (_c *MockClient_Increment_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockClient_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Increment_Call) Return(n int64, err error) *MockClient_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClient_Increment_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) (int64, error)) *MockClient_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockClient
func (_mock *MockClient) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *MockClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockClient_Set_Call {
	return &MockClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockClient_Set_Call) Run(run func(ctx context.Context, key string, value any, ttl time.Duration)) *MockClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Set_Call) Return(err error) *MockClient_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, ttl time.Duration) error) *MockClient_Set_Call {
	_c.Call.Return(run)
	return _c
}
