### Criando Order
POST http://localhost:8080/orders
Content-Type: application/json

{
    "price": 101.01,
    "tax": 11.5
}

### Listando Orders
GET http://localhost:8080/orders

### Listando Orders com API Key
GET http://localhost:8080/orders
API_KEY: TqQO9--1FUGsl4NqZDwNhdGhmJiuMFcPSKmwu4dZaY4


### Criando Tokens
POST http://localhost:8080/tokens
Content-Type: application/json

{
    "total_requests": 5
}


token:TqQO9--1FUGsl4NqZDwNhdGhmJiuMFcPSKmwu4dZaY4
token:TqQO9--1FUGsl4NqZDwNhdGhmJiuMFcPSKmwu4dZaY4