// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/dprio/redis-limiter/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Save(ctx context.Context, totalRequests int64) (domain.Token, error) {
	ret := _mock.Called(ctx, totalRequests)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Token, error)); ok {
		return returnFunc(ctx, totalRequests)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Token); ok {
		r0 = returnFunc(ctx, totalRequests)
	} else {
		r0 = ret.Get(0).(domain.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, totalRequests)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - totalRequests int64
func (_e *MockTokenRepository_Expecter) Save(ctx interface{}, totalRequests interface{}) *MockTokenRepository_Save_Call {
	return &MockTokenRepository_Save_Call{Call: _e.mock.On("Save", ctx, totalRequests)}
}

func (_c *MockTokenRepository_Save_Call) Run(run func(ctx context.Context, totalRequests int64)) *MockTokenRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Save_Call) Return(token domain.Token, err error) *MockTokenRepository_Save_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_Save_Call) RunAndReturn(run func(ctx context.Context, totalRequests int64) (domain.Token, error)) *MockTokenRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Update(ctx context.Context, token string, totalRequests int64) error {
	ret := _mock.Called(ctx, token, totalRequests)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, token, totalRequests)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - totalRequests int64
func (_e *MockTokenRepository_Expecter) Update(ctx interface{}, token interface{}, totalRequests interface{}) *MockTokenRepository_Update_Call {
	return &MockTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, token, totalRequests)}
}

func (_c *MockTokenRepository_Update_Call) Run(run func(ctx context.Context, token string, totalRequests int64)) *MockTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Update_Call) Return(err error) *MockTokenRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Update_Call) RunAndReturn(run func(ctx context.Context, token string, totalRequests int64) error) *MockTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Get(ctx context.Context, token string) (domain.Token, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Token, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Token); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenRepository_Expecter) Get(ctx interface{}, token interface{}) *MockTokenRepository_Get_Call {
	return &MockTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *MockTokenRepository_Get_Call) Run(run func(ctx context.Context, token string)) *MockTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Get_Call) Return(token1 domain.Token, err error) *MockTokenRepository_Get_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockTokenRepository_Get_Call) RunAndReturn(run func(ctx context.Context, token string) (domain.Token, error)) *MockTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
