// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ratelimiter

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLimiterGateway creates a new instance of MockLimiterGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiterGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiterGateway {
	mock := &MockLimiterGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimiterGateway is an autogenerated mock type for the LimiterGateway type
type MockLimiterGateway struct {
	mock.Mock
}

type MockLimiterGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiterGateway) EXPECT() *MockLimiterGateway_Expecter {
	return &MockLimiterGateway_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockLimiterGateway
func (_mock *MockLimiterGateway) Check(ctx context.Context, clientIP string, apiKey string) error {
	ret := _mock.Called(ctx, clientIP, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientIP, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimiterGateway_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockLimiterGateway_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - clientIP string
//   - apiKey string
func (_e *MockLimiterGateway_Expecter) Check(ctx interface{}, clientIP interface{}, apiKey interface{}) *MockLimiterGateway_Check_Call {
	return &MockLimiterGateway_Check_Call{Call: _e.mock.On("Check", ctx, clientIP, apiKey)}
}

func (_c *MockLimiterGateway_Check_Call) Run(run func(ctx context.Context, clientIP string, apiKey string)) *MockLimiterGateway_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLimiterGateway_Check_Call) Return(err error) *MockLimiterGateway_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimiterGateway_Check_Call) RunAndReturn(run func(ctx context.Context, clientIP string, apiKey string) error) *MockLimiterGateway_Check_Call {
	_c.Call.Return(run)
	return _c
}
