// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package createorder

import (
	"github.com/dprio/redis-limiter/pkg/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventCreator creates a new instance of MockEventCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventCreator {
	mock := &MockEventCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventCreator is an autogenerated mock type for the EventCreator type
type MockEventCreator struct {
	mock.Mock
}

type MockEventCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventCreator) EXPECT() *MockEventCreator_Expecter {
	return &MockEventCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventCreator
func (_mock *MockEventCreator) Create(payload any) events.Event {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 events.Event
	if returnFunc, ok := ret.Get(0).(func(any) events.Event); ok {
		r0 = returnFunc(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.Event)
		}
	}
	return r0
}

// MockEventCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - payload any
func (_e *MockEventCreator_Expecter) Create(payload interface{}) *MockEventCreator_Create_Call {
	return &MockEventCreator_Create_Call{Call: _e.mock.On("Create", payload)}
}

func (_c *MockEventCreator_Create_Call) Run(run func(payload any)) *MockEventCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventCreator_Create_Call) Return(event events.Event) *MockEventCreator_Create_Call {
	_c.Call.Return(event)
	return _c
}

func (_c *MockEventCreator_Create_Call) RunAndReturn(run func(payload any) events.Event) *MockEventCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}
